# Generated by Django 5.0.4 on 2024-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productcategories',
            index=models.Index(fields=['parent', 'order'], name='product_cat_parent__e41043_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategories',
            index=models.Index(fields=['order_by_site'], name='product_cat_order_b_255f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategories',
            index=models.Index(fields=['-is_available'], name='product_cat_is_avai_bb3174_idx'),
        ),
    ]
