# Generated by Django 5.0.4 on 2024-09-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategories_product_cat_parent__e41043_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productcategories',
            name='product_cat_parent__e41043_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategories',
            name='product_cat_order_b_255f6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategories',
            name='product_cat_is_avai_bb3174_idx',
        ),
    ]
