# Generated by Django 5.0.4 on 2024-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productcategories_product_cat_parent__e41043_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(db_index=True, max_length=550, verbose_name='Название категории'),
        ),
    ]
